version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nest-app:
    build:
      context: .
    image: nombre-de-tu-imagen
    container_name: nest-app
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge